import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import GlassDistortionFilter from "@/components/graphics/GlassDistortionFilter";
import ScrollRevealHeadingsLoader from "@/components/animations/ScrollRevealHeadingsLoader";
import SiteLoadGate from "@/components/layouts/SiteLoadGate";
import "./globals.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="scroll-reveal--enabled">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SiteLoadGate />
        <GlassDistortionFilter />
        <Header />
        <main id="main">{children}</main>
        <ScrollRevealHeadingsLoader />
        <Footer />
      </body>
    </html>
  );
}
